Add template for query
couchbaselabs/sirius pull request #54
Opened 2023-06-27 11:11 UTC by littlefermatlives

Added template for query over person dataset. Also increased the number of fields in person datasets

2023-06-27 12:03 UTC, manik-couchbase commented
Please resolve :-
```
sirius % make run  
Building Sirius
go build -o sirius ./cmd/api
# github.com/couchbaselabs/sirius/internal/template
internal/template/template_person.go:56:16: undefined: Queries
internal/template/template_person.go:57:16: undefined: Indexes
make: *** [build] Error 2
sirius % 
```

2023-06-27 12:10 UTC, manik-couchbase commented on internal/template/template_person.go
> +	Query         Queries   `json:"Query,omitempty"`
Person is the data model, Query and Index can be function but not the part of the data-model.
Person is the description of the document which is generated, It can't contain Query and Indexes.

2023-06-27 12:14 UTC, manik-couchbase requested changes

2023-06-27 12:35 UTC, littlefermatlives commented on internal/template/template_person.go
> +	Query         Queries   `json:"Query,omitempty"`
okay

2023-06-27 13:02 UTC, manik-couchbase commented on internal/template/template_person_query.go
> +func (P *Person) GetSampleQueries() (interface{}, error) {
As Queries  will be strings always, Instead of returning them in interface, directly return them as []string.
This will help to make it template agnostic and eliminate typecasting in tasks.

2023-06-27 15:29 UTC, manik-couchbase commented on internal/template/template_small_test.go
> +	_, err = template.GetSampleQueries()
Print queries as string to verify :D

2023-06-27 16:27 UTC, manik-couchbase requested changes

2023-06-27 16:27 UTC, manik-couchbase commented on internal/template/template.go
> +	GetSampleIndexes() (interface{}, error)
Rename the GetSampleIndexes() to GenerateIndex()

2023-06-27 16:27 UTC, manik-couchbase commented on internal/template/template.go
> +	GetSampleQueries() (interface{}, error)
Rename GetSampleQueries to GenerateQueries

2023-06-28 04:40 UTC, littlefermatlives commented on internal/template/template_person_query.go
> +func (P *Person) GetSampleQueries() (interface{}, error) {
I have put the list of queries inside a struct, so i'll have to send the struct pointer not as list of strings. Did you mean to remove the struct also?

2023-06-28 05:10 UTC, manik-couchbase commented on internal/template/template_person_query.go
> +func (P *Person) GetSampleQueries() (interface{}, error) {
Yes, keep it simple GenerateQueries will return a list of strings, these strings will be queries

2023-06-28 05:11 UTC, manik-couchbase commented on internal/template/template_person_query.go
> +func (P *Person) GenerateQueries() (interface{}, error) {
return []String{
.....
.....
.....
}

2023-06-28 05:23 UTC, littlefermatlives commented on internal/template/template_person_query.go
> +func (P *Person) GetSampleQueries() (interface{}, error) {
okay

2023-06-28 05:34 UTC, littlefermatlives commented on internal/template/template_person_query.go
> +func (P *Person) GenerateQueries() (interface{}, error) {
added, please take a look

2023-06-28 05:35 UTC, manik-couchbase commented on internal/template/template_person_query.go
> +func (P *Person) GenerateQueries() (interface{}, error) {
Thx 😄

2023-06-28 11:15 UTC, manik-couchbase requested changes

2023-06-28 11:15 UTC, manik-couchbase commented on internal/template/template_small.go
> +	return nil, nil
rerturn []string, nil instead of nil,nik

2023-06-28 11:20 UTC, manik-couchbase requested changes

2023-06-28 11:20 UTC, manik-couchbase commented on internal/template/template_person.go
> +	rand.Perm(len(hobbyChoices))
use faker instead of rand

2023-06-28 11:21 UTC, manik-couchbase requested changes

2023-06-28 11:21 UTC, manik-couchbase commented on internal/template/template_person_query.go
> +	queries := []string{
return  []string{....}, nil directly

2023-06-28 15:55 UTC, manik-couchbase requested changes
Complete the Update document part for the new fields of person tempalate

2023-06-28 15:55 UTC, manik-couchbase commented on internal/template/template_person.go
> +	colour    string `json:"colour,omitempty"`
colour should be Colour as it exposed in other packages. 
It is resulting in JSON decoding of GET operation result, as color is private variable.

2023-06-28 17:07 UTC, manik-couchbase approved these changes

2023-06-28 17:19 UTC, manik-couchbase requested changes

2023-06-28 17:19 UTC, manik-couchbase commented on internal/template/template_person.go
> +	if _, ok := checkFields["attributes.hair.color"]; ok || (len(checkFields) == 0) {
"attributes.hair.color" should be "attributes.hair.colour"

Check all the json tags correctly 😄

2023-06-28 17:49 UTC, littlefermatlives commented on internal/template/template_person.go
> +	if _, ok := checkFields["attributes.hair.color"]; ok || (len(checkFields) == 0) {
changed

2023-06-29 03:09 UTC, manik-couchbase approved these changes

2023-06-29 03:34 UTC, merged