Update :-
couchbaselabs/sirius pull request #55
Opened 2023-06-28 07:46 UTC by littlefermatlives

1. Add run template query endpoint in routes.go
2. Add run template query request handler in handlers.go
3. Add run template query task
4. Add task result for query task
5. Add SDK exceptions for qureyfailureexceptions

2023-06-28 08:10 UTC, manik-couchbase commented on cmd/api/handler.go
> +	log.Print(task, "Run Query")
log.Println(task, tasks.QueryOperation)

2023-06-28 08:11 UTC, manik-couchbase commented
I think task_query is missing in /internal/tasks/....

2023-06-28 08:24 UTC, littlefermatlives commented on cmd/api/handler.go
> +	log.Print(task, "Run Query")
updated

2023-06-29 04:22 UTC, manik-couchbase requested changes

2023-06-29 04:22 UTC, manik-couchbase commented on cmd/api/handler.go
> +
Add comment to describe function

2023-06-29 04:22 UTC, manik-couchbase commented on internal/task_result/task_result.go
> +type FailedQuery struct {
Add doc json tag for documentation.
Add the structs with correct naming at  https://github.com/couchbaselabs/sirius/blob/6fdcc5cbd2ca3a2b793cdb80d47efd63dff58d29/internal/generate/register.go#L36

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/helper.go
> +	template         string `json:"template,omitempty" doc:"true"`
make template string a public var

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/helper.go
> +		s.Duration = 100
make this 100 as a constant and can be declared as DefaultQueryRunTime

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	cluster, err := task.req.connectionManager.GetCluster(task.ClusterConfig)
Add a empty line here for better readability

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	manager := cluster.QueryIndexes()
Can be remaned as queryManager

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +func buildIndexSDKManager(cluster *gocb.Cluster, bucketName string, scopeName string, collectionName string, Type string, indexName string, fieldNameList []string) error {
Type as IndexType

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	if Type == "create primary index" {
"create primary index", "create index", "build index" declare them as constants

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +		err = manager.WatchIndexes(bucketName, indexesToBuild, time.Duration(120*time.Second), nil)
Make 120 as constant, can be WatchIndexesDuration

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	err = buildIndexSDKManager(cluster, task.Bucket, scope.Name(), collection.Name(),
This firstName, lastName is associated with a specific person template.
We have to make it specific template agnostic.

Let's say template.GetIndexFields() -> returns([]string , nameOfindex) which can be used to build indexes.

2023-06-29 04:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	err = buildIndexSDKManager(cluster, task.Bucket, scope.Name(), collection.Name(),
Put them in a loop,

for different_index_names, []feilds of that indexes -> create index

2023-06-29 13:09 UTC, littlefermatlives commented on cmd/api/handler.go
> +
added comment

2023-06-29 13:10 UTC, littlefermatlives commented on internal/task_result/task_result.go
> +type FailedQuery struct {
added

2023-06-29 13:10 UTC, littlefermatlives commented on internal/tasks/helper.go
> +	template         string `json:"template,omitempty" doc:"true"`
done

2023-06-29 13:12 UTC, littlefermatlives commented on internal/tasks/helper.go
> +		s.Duration = 100
done

2023-06-29 13:13 UTC, littlefermatlives commented on internal/tasks/task_run_query.go
> +func buildIndexSDKManager(cluster *gocb.Cluster, bucketName string, scopeName string, collectionName string, Type string, indexName string, fieldNameList []string) error {
done

2023-06-29 13:13 UTC, littlefermatlives commented on internal/tasks/task_run_query.go
> +	if Type == "create primary index" {
done

2023-06-29 13:13 UTC, littlefermatlives commented on internal/tasks/task_run_query.go
> +		err = manager.WatchIndexes(bucketName, indexesToBuild, time.Duration(120*time.Second), nil)
done

2023-06-29 13:13 UTC, littlefermatlives commented on internal/tasks/task_run_query.go
> +	err = buildIndexSDKManager(cluster, task.Bucket, scope.Name(), collection.Name(),
done

2023-06-30 08:12 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +	indexes, err := task.gen.Template.GenerateIndexesForSdk()
if indexes, err := task.gen.Template.GenerateIndexesForSdk(); err ! nil {
}

2023-06-30 08:22 UTC, manik-couchbase requested changes

2023-06-30 08:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +		log.Println("Get indexes for sdk failed.....")
return

2023-06-30 08:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +			"createIndex", indexName, indexFields)
use the constant which is declared

2023-06-30 08:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +				rows, err := cluster.Query(queries[i], &gocb.QueryOptions{})
if ; {
}

2023-06-30 08:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +func (task *QueryTask) BuildIdentifier() string {
Build Identifier cross check with task_insert
reference - https://github.com/couchbaselabs/sirius/blob/main/internal/tasks/task_bulk_insert.go#L46C1-L51C2

2023-06-30 08:22 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +func (task *QueryTask) Config(req *Request, seed int, seedEnd int, reRun bool) (int, error) {
cross check with new Config() implementation 
Reference - https://github.com/couchbaselabs/sirius/blob/main/internal/tasks/task_bulk_insert.go#L58

2023-06-30 10:54 UTC, manik-couchbase requested changes

2023-06-30 10:54 UTC, manik-couchbase commented on internal/tasks/task_run_query.go
> +		if task.IdentifierToken == "" {
remove IdentifierToken from here, We give it default value in BuildIdentifier()

2023-07-04 08:24 UTC, littlefermatlives commented on internal/tasks/task_run_query.go
> +		if task.IdentifierToken == "" {
removed

2023-07-04 08:26 UTC, manik-couchbase approved these changes

2023-07-04 08:30 UTC, merged